# Generated by Django 5.0.6 on 2024-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracked_products',
            field=models.ManyToManyField(blank=True, related_name='tracked_products', to='api.product'),
        ),
    ]
