# Generated by Django 5.0.6 on 2024-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_tracked_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cross_products',
            field=models.ManyToManyField(blank=True, related_name='related_cross_products', to='api.product'),
        ),
    ]
